// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GunsColumns holds the columns for the "guns" table.
	GunsColumns = []*schema.Column{
		{Name: "gun_id", Type: field.TypeInt, Increment: true},
		{Name: "gun_name", Type: field.TypeString, Size: 255},
		{Name: "year", Type: field.TypeInt, Nullable: true},
		{Name: "condition", Type: field.TypeInt, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "misc_attachments", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// GunsTable holds the schema information for the "guns" table.
	GunsTable = &schema.Table{
		Name:       "guns",
		Columns:    GunsColumns,
		PrimaryKey: []*schema.Column{GunsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GunsTable,
	}
)

func init() {
	GunsTable.Annotation = &entsql.Annotation{
		Table: "guns",
	}
}
