// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Antique-Inventory/ent/gun"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Gun is the model entity for the Gun schema.
type Gun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GunName holds the value of the "gun_name" field.
	GunName string `json:"gun_name,omitempty"`
	// Year holds the value of the "year" field.
	Year *int `json:"year,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition *int `json:"condition,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// MiscAttachments holds the value of the "misc_attachments" field.
	MiscAttachments string `json:"misc_attachments,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Gun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gun.FieldID, gun.FieldYear, gun.FieldCondition:
			values[i] = new(sql.NullInt64)
		case gun.FieldGunName, gun.FieldDescription, gun.FieldMiscAttachments:
			values[i] = new(sql.NullString)
		case gun.FieldCreatedAt, gun.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Gun fields.
func (_m *Gun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gun.FieldGunName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gun_name", values[i])
			} else if value.Valid {
				_m.GunName = value.String
			}
		case gun.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = new(int)
				*_m.Year = int(value.Int64)
			}
		case gun.FieldCondition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value.Valid {
				_m.Condition = new(int)
				*_m.Condition = int(value.Int64)
			}
		case gun.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case gun.FieldMiscAttachments:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field misc_attachments", values[i])
			} else if value.Valid {
				_m.MiscAttachments = value.String
			}
		case gun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Gun.
// This includes values selected through modifiers, order, etc.
func (_m *Gun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Gun.
// Note that you need to call Gun.Unwrap() before calling this method if this Gun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Gun) Update() *GunUpdateOne {
	return NewGunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Gun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Gun) Unwrap() *Gun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Gun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Gun) String() string {
	var builder strings.Builder
	builder.WriteString("Gun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("gun_name=")
	builder.WriteString(_m.GunName)
	builder.WriteString(", ")
	if v := _m.Year; v != nil {
		builder.WriteString("year=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Condition; v != nil {
		builder.WriteString("condition=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("misc_attachments=")
	builder.WriteString(_m.MiscAttachments)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Guns is a parsable slice of Gun.
type Guns []*Gun
