// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Antique-Inventory/ent/gun"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GunCreate is the builder for creating a Gun entity.
type GunCreate struct {
	config
	mutation *GunMutation
	hooks    []Hook
}

// SetGunName sets the "gun_name" field.
func (_c *GunCreate) SetGunName(v string) *GunCreate {
	_c.mutation.SetGunName(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *GunCreate) SetYear(v int) *GunCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_c *GunCreate) SetNillableYear(v *int) *GunCreate {
	if v != nil {
		_c.SetYear(*v)
	}
	return _c
}

// SetCondition sets the "condition" field.
func (_c *GunCreate) SetCondition(v int) *GunCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_c *GunCreate) SetNillableCondition(v *int) *GunCreate {
	if v != nil {
		_c.SetCondition(*v)
	}
	return _c
}

// SetSerialNumber sets the "serial_number" field.
func (_c *GunCreate) SetSerialNumber(v string) *GunCreate {
	_c.mutation.SetSerialNumber(v)
	return _c
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_c *GunCreate) SetNillableSerialNumber(v *string) *GunCreate {
	if v != nil {
		_c.SetSerialNumber(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *GunCreate) SetDescription(v string) *GunCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GunCreate) SetNillableDescription(v *string) *GunCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetImage sets the "image" field.
func (_c *GunCreate) SetImage(v []byte) *GunCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetMiscAttachments sets the "misc_attachments" field.
func (_c *GunCreate) SetMiscAttachments(v string) *GunCreate {
	_c.mutation.SetMiscAttachments(v)
	return _c
}

// SetNillableMiscAttachments sets the "misc_attachments" field if the given value is not nil.
func (_c *GunCreate) SetNillableMiscAttachments(v *string) *GunCreate {
	if v != nil {
		_c.SetMiscAttachments(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *GunCreate) SetValue(v float64) *GunCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *GunCreate) SetNillableValue(v *float64) *GunCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GunCreate) SetCreatedAt(v time.Time) *GunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GunCreate) SetNillableCreatedAt(v *time.Time) *GunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GunCreate) SetUpdatedAt(v time.Time) *GunCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GunCreate) SetNillableUpdatedAt(v *time.Time) *GunCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GunCreate) SetID(v int) *GunCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GunMutation object of the builder.
func (_c *GunCreate) Mutation() *GunMutation {
	return _c.mutation
}

// Save creates the Gun in the database.
func (_c *GunCreate) Save(ctx context.Context) (*Gun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GunCreate) SaveX(ctx context.Context) *Gun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GunCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := gun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := gun.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GunCreate) check() error {
	if _, ok := _c.mutation.GunName(); !ok {
		return &ValidationError{Name: "gun_name", err: errors.New(`ent: missing required field "Gun.gun_name"`)}
	}
	if v, ok := _c.mutation.GunName(); ok {
		if err := gun.GunNameValidator(v); err != nil {
			return &ValidationError{Name: "gun_name", err: fmt.Errorf(`ent: validator failed for field "Gun.gun_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SerialNumber(); ok {
		if err := gun.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Gun.serial_number": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := gun.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Gun.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MiscAttachments(); ok {
		if err := gun.MiscAttachmentsValidator(v); err != nil {
			return &ValidationError{Name: "misc_attachments", err: fmt.Errorf(`ent: validator failed for field "Gun.misc_attachments": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Gun.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Gun.updated_at"`)}
	}
	return nil
}

func (_c *GunCreate) sqlSave(ctx context.Context) (*Gun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GunCreate) createSpec() (*Gun, *sqlgraph.CreateSpec) {
	var (
		_node = &Gun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gun.Table, sqlgraph.NewFieldSpec(gun.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GunName(); ok {
		_spec.SetField(gun.FieldGunName, field.TypeString, value)
		_node.GunName = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(gun.FieldYear, field.TypeInt, value)
		_node.Year = &value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(gun.FieldCondition, field.TypeInt, value)
		_node.Condition = &value
	}
	if value, ok := _c.mutation.SerialNumber(); ok {
		_spec.SetField(gun.FieldSerialNumber, field.TypeString, value)
		_node.SerialNumber = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(gun.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(gun.FieldImage, field.TypeBytes, value)
		_node.Image = &value
	}
	if value, ok := _c.mutation.MiscAttachments(); ok {
		_spec.SetField(gun.FieldMiscAttachments, field.TypeString, value)
		_node.MiscAttachments = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(gun.FieldValue, field.TypeFloat64, value)
		_node.Value = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gun.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GunCreateBulk is the builder for creating many Gun entities in bulk.
type GunCreateBulk struct {
	config
	err      error
	builders []*GunCreate
}

// Save creates the Gun entities in the database.
func (_c *GunCreateBulk) Save(ctx context.Context) ([]*Gun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Gun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GunCreateBulk) SaveX(ctx context.Context) []*Gun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
