// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Antique-Inventory/ent/gun"
	"Antique-Inventory/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GunUpdate is the builder for updating Gun entities.
type GunUpdate struct {
	config
	hooks    []Hook
	mutation *GunMutation
}

// Where appends a list predicates to the GunUpdate builder.
func (_u *GunUpdate) Where(ps ...predicate.Gun) *GunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGunName sets the "gun_name" field.
func (_u *GunUpdate) SetGunName(v string) *GunUpdate {
	_u.mutation.SetGunName(v)
	return _u
}

// SetNillableGunName sets the "gun_name" field if the given value is not nil.
func (_u *GunUpdate) SetNillableGunName(v *string) *GunUpdate {
	if v != nil {
		_u.SetGunName(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *GunUpdate) SetYear(v int) *GunUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *GunUpdate) SetNillableYear(v *int) *GunUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *GunUpdate) AddYear(v int) *GunUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *GunUpdate) ClearYear() *GunUpdate {
	_u.mutation.ClearYear()
	return _u
}

// SetCondition sets the "condition" field.
func (_u *GunUpdate) SetCondition(v int) *GunUpdate {
	_u.mutation.ResetCondition()
	_u.mutation.SetCondition(v)
	return _u
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_u *GunUpdate) SetNillableCondition(v *int) *GunUpdate {
	if v != nil {
		_u.SetCondition(*v)
	}
	return _u
}

// AddCondition adds value to the "condition" field.
func (_u *GunUpdate) AddCondition(v int) *GunUpdate {
	_u.mutation.AddCondition(v)
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *GunUpdate) ClearCondition() *GunUpdate {
	_u.mutation.ClearCondition()
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *GunUpdate) SetSerialNumber(v string) *GunUpdate {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *GunUpdate) SetNillableSerialNumber(v *string) *GunUpdate {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (_u *GunUpdate) ClearSerialNumber() *GunUpdate {
	_u.mutation.ClearSerialNumber()
	return _u
}

// SetDescription sets the "description" field.
func (_u *GunUpdate) SetDescription(v string) *GunUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GunUpdate) SetNillableDescription(v *string) *GunUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GunUpdate) ClearDescription() *GunUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetImage sets the "image" field.
func (_u *GunUpdate) SetImage(v []byte) *GunUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *GunUpdate) ClearImage() *GunUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetMiscAttachments sets the "misc_attachments" field.
func (_u *GunUpdate) SetMiscAttachments(v string) *GunUpdate {
	_u.mutation.SetMiscAttachments(v)
	return _u
}

// SetNillableMiscAttachments sets the "misc_attachments" field if the given value is not nil.
func (_u *GunUpdate) SetNillableMiscAttachments(v *string) *GunUpdate {
	if v != nil {
		_u.SetMiscAttachments(*v)
	}
	return _u
}

// ClearMiscAttachments clears the value of the "misc_attachments" field.
func (_u *GunUpdate) ClearMiscAttachments() *GunUpdate {
	_u.mutation.ClearMiscAttachments()
	return _u
}

// SetValue sets the "value" field.
func (_u *GunUpdate) SetValue(v float64) *GunUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *GunUpdate) SetNillableValue(v *float64) *GunUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *GunUpdate) AddValue(v float64) *GunUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *GunUpdate) ClearValue() *GunUpdate {
	_u.mutation.ClearValue()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GunUpdate) SetUpdatedAt(v time.Time) *GunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GunMutation object of the builder.
func (_u *GunUpdate) Mutation() *GunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GunUpdate) check() error {
	if v, ok := _u.mutation.GunName(); ok {
		if err := gun.GunNameValidator(v); err != nil {
			return &ValidationError{Name: "gun_name", err: fmt.Errorf(`ent: validator failed for field "Gun.gun_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SerialNumber(); ok {
		if err := gun.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Gun.serial_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := gun.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Gun.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MiscAttachments(); ok {
		if err := gun.MiscAttachmentsValidator(v); err != nil {
			return &ValidationError{Name: "misc_attachments", err: fmt.Errorf(`ent: validator failed for field "Gun.misc_attachments": %w`, err)}
		}
	}
	return nil
}

func (_u *GunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gun.Table, gun.Columns, sqlgraph.NewFieldSpec(gun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GunName(); ok {
		_spec.SetField(gun.FieldGunName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(gun.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(gun.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(gun.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(gun.FieldCondition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCondition(); ok {
		_spec.AddField(gun.FieldCondition, field.TypeInt, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(gun.FieldCondition, field.TypeInt)
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(gun.FieldSerialNumber, field.TypeString, value)
	}
	if _u.mutation.SerialNumberCleared() {
		_spec.ClearField(gun.FieldSerialNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(gun.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(gun.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(gun.FieldImage, field.TypeBytes, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(gun.FieldImage, field.TypeBytes)
	}
	if value, ok := _u.mutation.MiscAttachments(); ok {
		_spec.SetField(gun.FieldMiscAttachments, field.TypeString, value)
	}
	if _u.mutation.MiscAttachmentsCleared() {
		_spec.ClearField(gun.FieldMiscAttachments, field.TypeString)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(gun.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(gun.FieldValue, field.TypeFloat64, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(gun.FieldValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gun.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GunUpdateOne is the builder for updating a single Gun entity.
type GunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GunMutation
}

// SetGunName sets the "gun_name" field.
func (_u *GunUpdateOne) SetGunName(v string) *GunUpdateOne {
	_u.mutation.SetGunName(v)
	return _u
}

// SetNillableGunName sets the "gun_name" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableGunName(v *string) *GunUpdateOne {
	if v != nil {
		_u.SetGunName(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *GunUpdateOne) SetYear(v int) *GunUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableYear(v *int) *GunUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *GunUpdateOne) AddYear(v int) *GunUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *GunUpdateOne) ClearYear() *GunUpdateOne {
	_u.mutation.ClearYear()
	return _u
}

// SetCondition sets the "condition" field.
func (_u *GunUpdateOne) SetCondition(v int) *GunUpdateOne {
	_u.mutation.ResetCondition()
	_u.mutation.SetCondition(v)
	return _u
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableCondition(v *int) *GunUpdateOne {
	if v != nil {
		_u.SetCondition(*v)
	}
	return _u
}

// AddCondition adds value to the "condition" field.
func (_u *GunUpdateOne) AddCondition(v int) *GunUpdateOne {
	_u.mutation.AddCondition(v)
	return _u
}

// ClearCondition clears the value of the "condition" field.
func (_u *GunUpdateOne) ClearCondition() *GunUpdateOne {
	_u.mutation.ClearCondition()
	return _u
}

// SetSerialNumber sets the "serial_number" field.
func (_u *GunUpdateOne) SetSerialNumber(v string) *GunUpdateOne {
	_u.mutation.SetSerialNumber(v)
	return _u
}

// SetNillableSerialNumber sets the "serial_number" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableSerialNumber(v *string) *GunUpdateOne {
	if v != nil {
		_u.SetSerialNumber(*v)
	}
	return _u
}

// ClearSerialNumber clears the value of the "serial_number" field.
func (_u *GunUpdateOne) ClearSerialNumber() *GunUpdateOne {
	_u.mutation.ClearSerialNumber()
	return _u
}

// SetDescription sets the "description" field.
func (_u *GunUpdateOne) SetDescription(v string) *GunUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableDescription(v *string) *GunUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GunUpdateOne) ClearDescription() *GunUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetImage sets the "image" field.
func (_u *GunUpdateOne) SetImage(v []byte) *GunUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *GunUpdateOne) ClearImage() *GunUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetMiscAttachments sets the "misc_attachments" field.
func (_u *GunUpdateOne) SetMiscAttachments(v string) *GunUpdateOne {
	_u.mutation.SetMiscAttachments(v)
	return _u
}

// SetNillableMiscAttachments sets the "misc_attachments" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableMiscAttachments(v *string) *GunUpdateOne {
	if v != nil {
		_u.SetMiscAttachments(*v)
	}
	return _u
}

// ClearMiscAttachments clears the value of the "misc_attachments" field.
func (_u *GunUpdateOne) ClearMiscAttachments() *GunUpdateOne {
	_u.mutation.ClearMiscAttachments()
	return _u
}

// SetValue sets the "value" field.
func (_u *GunUpdateOne) SetValue(v float64) *GunUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *GunUpdateOne) SetNillableValue(v *float64) *GunUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *GunUpdateOne) AddValue(v float64) *GunUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *GunUpdateOne) ClearValue() *GunUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GunUpdateOne) SetUpdatedAt(v time.Time) *GunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GunMutation object of the builder.
func (_u *GunUpdateOne) Mutation() *GunMutation {
	return _u.mutation
}

// Where appends a list predicates to the GunUpdate builder.
func (_u *GunUpdateOne) Where(ps ...predicate.Gun) *GunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GunUpdateOne) Select(field string, fields ...string) *GunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Gun entity.
func (_u *GunUpdateOne) Save(ctx context.Context) (*Gun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GunUpdateOne) SaveX(ctx context.Context) *Gun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GunUpdateOne) check() error {
	if v, ok := _u.mutation.GunName(); ok {
		if err := gun.GunNameValidator(v); err != nil {
			return &ValidationError{Name: "gun_name", err: fmt.Errorf(`ent: validator failed for field "Gun.gun_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SerialNumber(); ok {
		if err := gun.SerialNumberValidator(v); err != nil {
			return &ValidationError{Name: "serial_number", err: fmt.Errorf(`ent: validator failed for field "Gun.serial_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := gun.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Gun.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MiscAttachments(); ok {
		if err := gun.MiscAttachmentsValidator(v); err != nil {
			return &ValidationError{Name: "misc_attachments", err: fmt.Errorf(`ent: validator failed for field "Gun.misc_attachments": %w`, err)}
		}
	}
	return nil
}

func (_u *GunUpdateOne) sqlSave(ctx context.Context) (_node *Gun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gun.Table, gun.Columns, sqlgraph.NewFieldSpec(gun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Gun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gun.FieldID)
		for _, f := range fields {
			if !gun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GunName(); ok {
		_spec.SetField(gun.FieldGunName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(gun.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(gun.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(gun.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.Condition(); ok {
		_spec.SetField(gun.FieldCondition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCondition(); ok {
		_spec.AddField(gun.FieldCondition, field.TypeInt, value)
	}
	if _u.mutation.ConditionCleared() {
		_spec.ClearField(gun.FieldCondition, field.TypeInt)
	}
	if value, ok := _u.mutation.SerialNumber(); ok {
		_spec.SetField(gun.FieldSerialNumber, field.TypeString, value)
	}
	if _u.mutation.SerialNumberCleared() {
		_spec.ClearField(gun.FieldSerialNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(gun.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(gun.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(gun.FieldImage, field.TypeBytes, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(gun.FieldImage, field.TypeBytes)
	}
	if value, ok := _u.mutation.MiscAttachments(); ok {
		_spec.SetField(gun.FieldMiscAttachments, field.TypeString, value)
	}
	if _u.mutation.MiscAttachmentsCleared() {
		_spec.ClearField(gun.FieldMiscAttachments, field.TypeString)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(gun.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(gun.FieldValue, field.TypeFloat64, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(gun.FieldValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gun.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Gun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
