// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Antique-Inventory/ent/gun"
	"Antique-Inventory/ent/predicate"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeGun = "Gun"
)

// GunMutation represents an operation that mutates the Gun nodes in the graph.
type GunMutation struct {
	config
	op               Op
	typ              string
	id               *int
	gun_name         *string
	year             *int
	addyear          *int
	condition        *int
	addcondition     *int
	description      *string
	misc_attachments *string
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*Gun, error)
	predicates       []predicate.Gun
}

var _ ent.Mutation = (*GunMutation)(nil)

// gunOption allows management of the mutation configuration using functional options.
type gunOption func(*GunMutation)

// newGunMutation creates new mutation for the Gun entity.
func newGunMutation(c config, op Op, opts ...gunOption) *GunMutation {
	m := &GunMutation{
		config:        c,
		op:            op,
		typ:           TypeGun,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withGunID sets the ID field of the mutation.
func withGunID(id int) gunOption {
	return func(m *GunMutation) {
		var (
			err   error
			once  sync.Once
			value *Gun
		)
		m.oldValue = func(ctx context.Context) (*Gun, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Gun.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withGun sets the old Gun of the mutation.
func withGun(node *Gun) gunOption {
	return func(m *GunMutation) {
		m.oldValue = func(context.Context) (*Gun, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m GunMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m GunMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Gun entities.
func (m *GunMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *GunMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *GunMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Gun.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGunName sets the "gun_name" field.
func (m *GunMutation) SetGunName(s string) {
	m.gun_name = &s
}

// GunName returns the value of the "gun_name" field in the mutation.
func (m *GunMutation) GunName() (r string, exists bool) {
	v := m.gun_name
	if v == nil {
		return
	}
	return *v, true
}

// OldGunName returns the old "gun_name" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldGunName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGunName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGunName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGunName: %w", err)
	}
	return oldValue.GunName, nil
}

// ResetGunName resets all changes to the "gun_name" field.
func (m *GunMutation) ResetGunName() {
	m.gun_name = nil
}

// SetYear sets the "year" field.
func (m *GunMutation) SetYear(i int) {
	m.year = &i
	m.addyear = nil
}

// Year returns the value of the "year" field in the mutation.
func (m *GunMutation) Year() (r int, exists bool) {
	v := m.year
	if v == nil {
		return
	}
	return *v, true
}

// OldYear returns the old "year" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldYear(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldYear is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldYear requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldYear: %w", err)
	}
	return oldValue.Year, nil
}

// AddYear adds i to the "year" field.
func (m *GunMutation) AddYear(i int) {
	if m.addyear != nil {
		*m.addyear += i
	} else {
		m.addyear = &i
	}
}

// AddedYear returns the value that was added to the "year" field in this mutation.
func (m *GunMutation) AddedYear() (r int, exists bool) {
	v := m.addyear
	if v == nil {
		return
	}
	return *v, true
}

// ClearYear clears the value of the "year" field.
func (m *GunMutation) ClearYear() {
	m.year = nil
	m.addyear = nil
	m.clearedFields[gun.FieldYear] = struct{}{}
}

// YearCleared returns if the "year" field was cleared in this mutation.
func (m *GunMutation) YearCleared() bool {
	_, ok := m.clearedFields[gun.FieldYear]
	return ok
}

// ResetYear resets all changes to the "year" field.
func (m *GunMutation) ResetYear() {
	m.year = nil
	m.addyear = nil
	delete(m.clearedFields, gun.FieldYear)
}

// SetCondition sets the "condition" field.
func (m *GunMutation) SetCondition(i int) {
	m.condition = &i
	m.addcondition = nil
}

// Condition returns the value of the "condition" field in the mutation.
func (m *GunMutation) Condition() (r int, exists bool) {
	v := m.condition
	if v == nil {
		return
	}
	return *v, true
}

// OldCondition returns the old "condition" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldCondition(ctx context.Context) (v *int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCondition is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCondition requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCondition: %w", err)
	}
	return oldValue.Condition, nil
}

// AddCondition adds i to the "condition" field.
func (m *GunMutation) AddCondition(i int) {
	if m.addcondition != nil {
		*m.addcondition += i
	} else {
		m.addcondition = &i
	}
}

// AddedCondition returns the value that was added to the "condition" field in this mutation.
func (m *GunMutation) AddedCondition() (r int, exists bool) {
	v := m.addcondition
	if v == nil {
		return
	}
	return *v, true
}

// ClearCondition clears the value of the "condition" field.
func (m *GunMutation) ClearCondition() {
	m.condition = nil
	m.addcondition = nil
	m.clearedFields[gun.FieldCondition] = struct{}{}
}

// ConditionCleared returns if the "condition" field was cleared in this mutation.
func (m *GunMutation) ConditionCleared() bool {
	_, ok := m.clearedFields[gun.FieldCondition]
	return ok
}

// ResetCondition resets all changes to the "condition" field.
func (m *GunMutation) ResetCondition() {
	m.condition = nil
	m.addcondition = nil
	delete(m.clearedFields, gun.FieldCondition)
}

// SetDescription sets the "description" field.
func (m *GunMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *GunMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *GunMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[gun.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *GunMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[gun.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *GunMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, gun.FieldDescription)
}

// SetMiscAttachments sets the "misc_attachments" field.
func (m *GunMutation) SetMiscAttachments(s string) {
	m.misc_attachments = &s
}

// MiscAttachments returns the value of the "misc_attachments" field in the mutation.
func (m *GunMutation) MiscAttachments() (r string, exists bool) {
	v := m.misc_attachments
	if v == nil {
		return
	}
	return *v, true
}

// OldMiscAttachments returns the old "misc_attachments" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldMiscAttachments(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMiscAttachments is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMiscAttachments requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMiscAttachments: %w", err)
	}
	return oldValue.MiscAttachments, nil
}

// ClearMiscAttachments clears the value of the "misc_attachments" field.
func (m *GunMutation) ClearMiscAttachments() {
	m.misc_attachments = nil
	m.clearedFields[gun.FieldMiscAttachments] = struct{}{}
}

// MiscAttachmentsCleared returns if the "misc_attachments" field was cleared in this mutation.
func (m *GunMutation) MiscAttachmentsCleared() bool {
	_, ok := m.clearedFields[gun.FieldMiscAttachments]
	return ok
}

// ResetMiscAttachments resets all changes to the "misc_attachments" field.
func (m *GunMutation) ResetMiscAttachments() {
	m.misc_attachments = nil
	delete(m.clearedFields, gun.FieldMiscAttachments)
}

// SetCreatedAt sets the "created_at" field.
func (m *GunMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *GunMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *GunMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *GunMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *GunMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Gun entity.
// If the Gun object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GunMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *GunMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the GunMutation builder.
func (m *GunMutation) Where(ps ...predicate.Gun) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the GunMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *GunMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Gun, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *GunMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *GunMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Gun).
func (m *GunMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *GunMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.gun_name != nil {
		fields = append(fields, gun.FieldGunName)
	}
	if m.year != nil {
		fields = append(fields, gun.FieldYear)
	}
	if m.condition != nil {
		fields = append(fields, gun.FieldCondition)
	}
	if m.description != nil {
		fields = append(fields, gun.FieldDescription)
	}
	if m.misc_attachments != nil {
		fields = append(fields, gun.FieldMiscAttachments)
	}
	if m.created_at != nil {
		fields = append(fields, gun.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, gun.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *GunMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case gun.FieldGunName:
		return m.GunName()
	case gun.FieldYear:
		return m.Year()
	case gun.FieldCondition:
		return m.Condition()
	case gun.FieldDescription:
		return m.Description()
	case gun.FieldMiscAttachments:
		return m.MiscAttachments()
	case gun.FieldCreatedAt:
		return m.CreatedAt()
	case gun.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *GunMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case gun.FieldGunName:
		return m.OldGunName(ctx)
	case gun.FieldYear:
		return m.OldYear(ctx)
	case gun.FieldCondition:
		return m.OldCondition(ctx)
	case gun.FieldDescription:
		return m.OldDescription(ctx)
	case gun.FieldMiscAttachments:
		return m.OldMiscAttachments(ctx)
	case gun.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case gun.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Gun field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GunMutation) SetField(name string, value ent.Value) error {
	switch name {
	case gun.FieldGunName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGunName(v)
		return nil
	case gun.FieldYear:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetYear(v)
		return nil
	case gun.FieldCondition:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCondition(v)
		return nil
	case gun.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case gun.FieldMiscAttachments:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMiscAttachments(v)
		return nil
	case gun.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case gun.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Gun field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *GunMutation) AddedFields() []string {
	var fields []string
	if m.addyear != nil {
		fields = append(fields, gun.FieldYear)
	}
	if m.addcondition != nil {
		fields = append(fields, gun.FieldCondition)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *GunMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case gun.FieldYear:
		return m.AddedYear()
	case gun.FieldCondition:
		return m.AddedCondition()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GunMutation) AddField(name string, value ent.Value) error {
	switch name {
	case gun.FieldYear:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddYear(v)
		return nil
	case gun.FieldCondition:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCondition(v)
		return nil
	}
	return fmt.Errorf("unknown Gun numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *GunMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(gun.FieldYear) {
		fields = append(fields, gun.FieldYear)
	}
	if m.FieldCleared(gun.FieldCondition) {
		fields = append(fields, gun.FieldCondition)
	}
	if m.FieldCleared(gun.FieldDescription) {
		fields = append(fields, gun.FieldDescription)
	}
	if m.FieldCleared(gun.FieldMiscAttachments) {
		fields = append(fields, gun.FieldMiscAttachments)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *GunMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *GunMutation) ClearField(name string) error {
	switch name {
	case gun.FieldYear:
		m.ClearYear()
		return nil
	case gun.FieldCondition:
		m.ClearCondition()
		return nil
	case gun.FieldDescription:
		m.ClearDescription()
		return nil
	case gun.FieldMiscAttachments:
		m.ClearMiscAttachments()
		return nil
	}
	return fmt.Errorf("unknown Gun nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *GunMutation) ResetField(name string) error {
	switch name {
	case gun.FieldGunName:
		m.ResetGunName()
		return nil
	case gun.FieldYear:
		m.ResetYear()
		return nil
	case gun.FieldCondition:
		m.ResetCondition()
		return nil
	case gun.FieldDescription:
		m.ResetDescription()
		return nil
	case gun.FieldMiscAttachments:
		m.ResetMiscAttachments()
		return nil
	case gun.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case gun.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Gun field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *GunMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *GunMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *GunMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *GunMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *GunMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *GunMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *GunMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Gun unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *GunMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Gun edge %s", name)
}
