// Code generated by ent, DO NOT EDIT.

package gun

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gun type in the database.
	Label = "gun"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "gun_id"
	// FieldGunName holds the string denoting the gun_name field in the database.
	FieldGunName = "gun_name"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMiscAttachments holds the string denoting the misc_attachments field in the database.
	FieldMiscAttachments = "misc_attachments"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updatedAt"
	// Table holds the table name of the gun in the database.
	Table = "guns"
)

// Columns holds all SQL columns for gun fields.
var Columns = []string{
	FieldID,
	FieldGunName,
	FieldYear,
	FieldCondition,
	FieldDescription,
	FieldMiscAttachments,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GunNameValidator is a validator for the "gun_name" field. It is called by the builders before save.
	GunNameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// MiscAttachmentsValidator is a validator for the "misc_attachments" field. It is called by the builders before save.
	MiscAttachmentsValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Gun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGunName orders the results by the gun_name field.
func ByGunName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGunName, opts...).ToFunc()
}

// ByYear orders the results by the year field.
func ByYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYear, opts...).ToFunc()
}

// ByCondition orders the results by the condition field.
func ByCondition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCondition, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMiscAttachments orders the results by the misc_attachments field.
func ByMiscAttachments(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMiscAttachments, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
