// Code generated by ent, DO NOT EDIT.

package gun

import (
	"Antique-Inventory/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldID, id))
}

// GunName applies equality check predicate on the "gun_name" field. It's identical to GunNameEQ.
func GunName(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldGunName, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldYear, v))
}

// Condition applies equality check predicate on the "condition" field. It's identical to ConditionEQ.
func Condition(v int) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldCondition, v))
}

// SerialNumber applies equality check predicate on the "serial_number" field. It's identical to SerialNumberEQ.
func SerialNumber(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldSerialNumber, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldDescription, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldImage, v))
}

// MiscAttachments applies equality check predicate on the "misc_attachments" field. It's identical to MiscAttachmentsEQ.
func MiscAttachments(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldMiscAttachments, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldValue, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldUpdatedAt, v))
}

// GunNameEQ applies the EQ predicate on the "gun_name" field.
func GunNameEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldGunName, v))
}

// GunNameNEQ applies the NEQ predicate on the "gun_name" field.
func GunNameNEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldGunName, v))
}

// GunNameIn applies the In predicate on the "gun_name" field.
func GunNameIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldGunName, vs...))
}

// GunNameNotIn applies the NotIn predicate on the "gun_name" field.
func GunNameNotIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldGunName, vs...))
}

// GunNameGT applies the GT predicate on the "gun_name" field.
func GunNameGT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldGunName, v))
}

// GunNameGTE applies the GTE predicate on the "gun_name" field.
func GunNameGTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldGunName, v))
}

// GunNameLT applies the LT predicate on the "gun_name" field.
func GunNameLT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldGunName, v))
}

// GunNameLTE applies the LTE predicate on the "gun_name" field.
func GunNameLTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldGunName, v))
}

// GunNameContains applies the Contains predicate on the "gun_name" field.
func GunNameContains(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContains(FieldGunName, v))
}

// GunNameHasPrefix applies the HasPrefix predicate on the "gun_name" field.
func GunNameHasPrefix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasPrefix(FieldGunName, v))
}

// GunNameHasSuffix applies the HasSuffix predicate on the "gun_name" field.
func GunNameHasSuffix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasSuffix(FieldGunName, v))
}

// GunNameEqualFold applies the EqualFold predicate on the "gun_name" field.
func GunNameEqualFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEqualFold(FieldGunName, v))
}

// GunNameContainsFold applies the ContainsFold predicate on the "gun_name" field.
func GunNameContainsFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContainsFold(FieldGunName, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldYear, v))
}

// YearIsNil applies the IsNil predicate on the "year" field.
func YearIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldYear))
}

// YearNotNil applies the NotNil predicate on the "year" field.
func YearNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldYear))
}

// ConditionEQ applies the EQ predicate on the "condition" field.
func ConditionEQ(v int) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldCondition, v))
}

// ConditionNEQ applies the NEQ predicate on the "condition" field.
func ConditionNEQ(v int) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldCondition, v))
}

// ConditionIn applies the In predicate on the "condition" field.
func ConditionIn(vs ...int) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldCondition, vs...))
}

// ConditionNotIn applies the NotIn predicate on the "condition" field.
func ConditionNotIn(vs ...int) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldCondition, vs...))
}

// ConditionGT applies the GT predicate on the "condition" field.
func ConditionGT(v int) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldCondition, v))
}

// ConditionGTE applies the GTE predicate on the "condition" field.
func ConditionGTE(v int) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldCondition, v))
}

// ConditionLT applies the LT predicate on the "condition" field.
func ConditionLT(v int) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldCondition, v))
}

// ConditionLTE applies the LTE predicate on the "condition" field.
func ConditionLTE(v int) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldCondition, v))
}

// ConditionIsNil applies the IsNil predicate on the "condition" field.
func ConditionIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldCondition))
}

// ConditionNotNil applies the NotNil predicate on the "condition" field.
func ConditionNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldCondition))
}

// SerialNumberEQ applies the EQ predicate on the "serial_number" field.
func SerialNumberEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldSerialNumber, v))
}

// SerialNumberNEQ applies the NEQ predicate on the "serial_number" field.
func SerialNumberNEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldSerialNumber, v))
}

// SerialNumberIn applies the In predicate on the "serial_number" field.
func SerialNumberIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldSerialNumber, vs...))
}

// SerialNumberNotIn applies the NotIn predicate on the "serial_number" field.
func SerialNumberNotIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldSerialNumber, vs...))
}

// SerialNumberGT applies the GT predicate on the "serial_number" field.
func SerialNumberGT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldSerialNumber, v))
}

// SerialNumberGTE applies the GTE predicate on the "serial_number" field.
func SerialNumberGTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldSerialNumber, v))
}

// SerialNumberLT applies the LT predicate on the "serial_number" field.
func SerialNumberLT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldSerialNumber, v))
}

// SerialNumberLTE applies the LTE predicate on the "serial_number" field.
func SerialNumberLTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldSerialNumber, v))
}

// SerialNumberContains applies the Contains predicate on the "serial_number" field.
func SerialNumberContains(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContains(FieldSerialNumber, v))
}

// SerialNumberHasPrefix applies the HasPrefix predicate on the "serial_number" field.
func SerialNumberHasPrefix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasPrefix(FieldSerialNumber, v))
}

// SerialNumberHasSuffix applies the HasSuffix predicate on the "serial_number" field.
func SerialNumberHasSuffix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasSuffix(FieldSerialNumber, v))
}

// SerialNumberIsNil applies the IsNil predicate on the "serial_number" field.
func SerialNumberIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldSerialNumber))
}

// SerialNumberNotNil applies the NotNil predicate on the "serial_number" field.
func SerialNumberNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldSerialNumber))
}

// SerialNumberEqualFold applies the EqualFold predicate on the "serial_number" field.
func SerialNumberEqualFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEqualFold(FieldSerialNumber, v))
}

// SerialNumberContainsFold applies the ContainsFold predicate on the "serial_number" field.
func SerialNumberContainsFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContainsFold(FieldSerialNumber, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContainsFold(FieldDescription, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...[]byte) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...[]byte) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v []byte) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldImage))
}

// MiscAttachmentsEQ applies the EQ predicate on the "misc_attachments" field.
func MiscAttachmentsEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldMiscAttachments, v))
}

// MiscAttachmentsNEQ applies the NEQ predicate on the "misc_attachments" field.
func MiscAttachmentsNEQ(v string) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldMiscAttachments, v))
}

// MiscAttachmentsIn applies the In predicate on the "misc_attachments" field.
func MiscAttachmentsIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldMiscAttachments, vs...))
}

// MiscAttachmentsNotIn applies the NotIn predicate on the "misc_attachments" field.
func MiscAttachmentsNotIn(vs ...string) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldMiscAttachments, vs...))
}

// MiscAttachmentsGT applies the GT predicate on the "misc_attachments" field.
func MiscAttachmentsGT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldMiscAttachments, v))
}

// MiscAttachmentsGTE applies the GTE predicate on the "misc_attachments" field.
func MiscAttachmentsGTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldMiscAttachments, v))
}

// MiscAttachmentsLT applies the LT predicate on the "misc_attachments" field.
func MiscAttachmentsLT(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldMiscAttachments, v))
}

// MiscAttachmentsLTE applies the LTE predicate on the "misc_attachments" field.
func MiscAttachmentsLTE(v string) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldMiscAttachments, v))
}

// MiscAttachmentsContains applies the Contains predicate on the "misc_attachments" field.
func MiscAttachmentsContains(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContains(FieldMiscAttachments, v))
}

// MiscAttachmentsHasPrefix applies the HasPrefix predicate on the "misc_attachments" field.
func MiscAttachmentsHasPrefix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasPrefix(FieldMiscAttachments, v))
}

// MiscAttachmentsHasSuffix applies the HasSuffix predicate on the "misc_attachments" field.
func MiscAttachmentsHasSuffix(v string) predicate.Gun {
	return predicate.Gun(sql.FieldHasSuffix(FieldMiscAttachments, v))
}

// MiscAttachmentsIsNil applies the IsNil predicate on the "misc_attachments" field.
func MiscAttachmentsIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldMiscAttachments))
}

// MiscAttachmentsNotNil applies the NotNil predicate on the "misc_attachments" field.
func MiscAttachmentsNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldMiscAttachments))
}

// MiscAttachmentsEqualFold applies the EqualFold predicate on the "misc_attachments" field.
func MiscAttachmentsEqualFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldEqualFold(FieldMiscAttachments, v))
}

// MiscAttachmentsContainsFold applies the ContainsFold predicate on the "misc_attachments" field.
func MiscAttachmentsContainsFold(v string) predicate.Gun {
	return predicate.Gun(sql.FieldContainsFold(FieldMiscAttachments, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.Gun {
	return predicate.Gun(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.Gun {
	return predicate.Gun(sql.FieldNotNull(FieldValue))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Gun {
	return predicate.Gun(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Gun) predicate.Gun {
	return predicate.Gun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Gun) predicate.Gun {
	return predicate.Gun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Gun) predicate.Gun {
	return predicate.Gun(sql.NotPredicates(p))
}
